import Link from "next/link";
import { LogoutButton } from "@/components/ui/logout-button";
import { prisma } from "@/lib/prisma";
import { changeUserRoleAction, createUserAction, resetUserPasswordAction, toggleUserActiveAction } from "./actions";

const ROLE_LABELS = { ADMIN: "Administrador", DEV: "Desarrollador", CLIENT: "Cliente" } as const;

export default async function UsersPage({ searchParams }: { searchParams?: Promise<Record<string, string | string[] | undefined>> }) {
  const params = (await searchParams) ?? {};
  const success = typeof params.success === "string" ? params.success : null;
  const error = typeof params.error === "string" ? params.error : null;
  const users = await prisma.user.findMany({
    orderBy: [{ globalRole: "asc" }, { name: "asc" }],
    include: { memberships: { include: { project: { select: { name: true } } }, orderBy: { createdAt: "asc" } } },
  });

  return <main className="min-h-screen bg-zinc-50"><div className="mx-auto max-w-7xl px-6 py-8">
    <header className="mb-7 flex flex-col gap-3 border-b border-zinc-200 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-zinc-500">Senda · administración</p><h1 className="text-2xl font-semibold text-zinc-950">Usuarios y accesos</h1><p className="mt-1 text-sm text-zinc-600">Creá cuentas, definí su alcance y revocá acceso de forma segura.</p></div><div className="flex items-center gap-4"><Link href="/admin/projects" className="text-sm font-medium text-zinc-600">Proyectos</Link><Link href="/workspace" className="text-sm font-medium text-zinc-600">Workspace dev</Link><LogoutButton /></div></header>
    {success ? <p className="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{success}</p> : null}{error ? <p className="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</p> : null}
    <section className="mb-7 rounded-2xl border bg-white p-5"><h2 className="font-semibold">Nueva cuenta</h2><form action={createUserAction} className="mt-4 grid gap-3 lg:grid-cols-[1fr_1fr_1fr_180px_auto]"><input name="name" required maxLength={120} placeholder="Nombre" className="rounded-xl border px-3 py-2.5 text-sm" /><input name="email" type="email" required maxLength={320} placeholder="email@empresa.com" className="rounded-xl border px-3 py-2.5 text-sm" /><input name="password" type="password" required minLength={8} placeholder="Contraseña temporal" className="rounded-xl border px-3 py-2.5 text-sm" /><select name="role" defaultValue="DEV" className="rounded-xl border px-3 py-2.5 text-sm"><option value="ADMIN">Administrador</option><option value="DEV">Desarrollador</option><option value="CLIENT">Cliente</option></select><button className="rounded-xl bg-[var(--navy)] px-4 py-2.5 text-sm font-semibold text-white">Crear cuenta</button></form></section>
    <section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b px-5 py-4"><h2 className="font-semibold">Cuentas existentes ({users.length})</h2></div><div className="divide-y">{users.map((user) => <article key={user.id} className="grid gap-4 p-5 lg:grid-cols-[minmax(0,1fr)_190px_250px]"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-zinc-950">{user.name}</h3><span className={`rounded-full px-2 py-1 text-xs font-bold ${user.isActive ? "bg-emerald-50 text-emerald-700" : "bg-zinc-100 text-zinc-600"}`}>{user.isActive ? "Activa" : "Desactivada"}</span></div><p className="mt-1 text-sm text-zinc-600">{user.email}</p><p className="mt-2 text-xs text-zinc-500">Proyectos: {user.memberships.map((membership) => membership.project.name).join(", ") || "Sin asignar"}</p></div><form action={changeUserRoleAction} className="flex items-center gap-2"><input type="hidden" name="userId" value={user.id} /><select name="role" defaultValue={user.globalRole} className="min-w-0 flex-1 rounded-lg border px-2 py-2 text-sm"><option value="ADMIN">{ROLE_LABELS.ADMIN}</option><option value="DEV">{ROLE_LABELS.DEV}</option><option value="CLIENT">{ROLE_LABELS.CLIENT}</option></select><button className="rounded-lg border px-3 py-2 text-xs font-semibold">Guardar</button></form><div className="flex flex-wrap items-center gap-2"><form action={resetUserPasswordAction} className="flex min-w-[180px] flex-1 gap-2"><input type="hidden" name="userId" value={user.id} /><input name="password" type="password" minLength={8} required placeholder="Nueva contraseña" className="min-w-0 flex-1 rounded-lg border px-2 py-2 text-xs" /><button className="rounded-lg border px-3 py-2 text-xs font-semibold">Resetear</button></form><form action={toggleUserActiveAction}><input type="hidden" name="userId" value={user.id} /><input type="hidden" name="active" value={String(!user.isActive)} /><button className={`rounded-lg px-3 py-2 text-xs font-semibold ${user.isActive ? "border border-red-200 text-red-700" : "bg-emerald-600 text-white"}`}>{user.isActive ? "Desactivar" : "Activar"}</button></form></div></article>)}</div></section>
  </div></main>;
}
