CREATE TYPE "ProjectConversationKind" AS ENUM ('DIRECT');
CREATE TABLE "ProjectConversation" ("id" TEXT NOT NULL, "projectId" TEXT NOT NULL, "kind" "ProjectConversationKind" NOT NULL DEFAULT 'DIRECT', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ProjectConversation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProjectConversationMember" ("id" TEXT NOT NULL, "conversationId" TEXT NOT NULL, "userId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ProjectConversationMember_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AssistantSession" ("id" TEXT NOT NULL, "projectId" TEXT NOT NULL, "userId" TEXT NOT NULL, "title" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AssistantSession_pkey" PRIMARY KEY ("id"));
ALTER TABLE "Message" ADD COLUMN "conversationId" TEXT;
ALTER TABLE "ProjectContextChunk" ADD COLUMN "assistantSessionId" TEXT;
CREATE UNIQUE INDEX "ProjectConversationMember_conversationId_userId_key" ON "ProjectConversationMember"("conversationId", "userId");
CREATE INDEX "ProjectConversation_projectId_updatedAt_idx" ON "ProjectConversation"("projectId", "updatedAt");
CREATE INDEX "ProjectConversationMember_userId_idx" ON "ProjectConversationMember"("userId");
CREATE INDEX "AssistantSession_projectId_userId_updatedAt_idx" ON "AssistantSession"("projectId", "userId", "updatedAt");
CREATE INDEX "Message_conversationId_createdAt_idx" ON "Message"("conversationId", "createdAt");
CREATE INDEX "ProjectContextChunk_assistantSessionId_createdAt_idx" ON "ProjectContextChunk"("assistantSessionId", "createdAt");
ALTER TABLE "ProjectConversation" ADD CONSTRAINT "ProjectConversation_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProjectConversationMember" ADD CONSTRAINT "ProjectConversationMember_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "ProjectConversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProjectConversationMember" ADD CONSTRAINT "ProjectConversationMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AssistantSession" ADD CONSTRAINT "AssistantSession_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AssistantSession" ADD CONSTRAINT "AssistantSession_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Message" ADD CONSTRAINT "Message_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "ProjectConversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProjectContextChunk" ADD CONSTRAINT "ProjectContextChunk_assistantSessionId_fkey" FOREIGN KEY ("assistantSessionId") REFERENCES "AssistantSession"("id") ON DELETE CASCADE ON UPDATE CASCADE;
