"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export function ProposalDetail({ proposal, canSubmit }: { proposal: { id: string; title: string; description: string; summary: string | null; openQuestions: string | null; status: string; createdById: string | null; messages: Array<{ id: string; body: string; author: string; createdAt: string }> }; canSubmit: boolean }) {
  const router = useRouter(); const [error, setError] = useState<string | null>(null); const [sending, setSending] = useState(false);
  async function submit() { setSending(true); const response = await fetch(`/api/proposals/${proposal.id}/submit`, { method: "POST" }); const data = await response.json().catch(() => null) as { error?: string } | null; setSending(false); if (!response.ok) setError(data?.error ?? "No se pudo enviar."); else router.refresh(); }
  return <main className="mx-auto min-h-screen max-w-3xl px-6 py-10"><p className="text-xs font-bold uppercase tracking-[.14em] text-teal-700">Propuesta</p><div className="mt-3 rounded-2xl border border-[var(--border-soft)] bg-[var(--surface)] p-6"><div className="flex items-start justify-between gap-4"><h1 className="text-2xl font-semibold">{proposal.title}</h1><span className="rounded-full bg-[var(--brand-soft)] px-3 py-1 text-xs font-semibold text-[var(--brand-strong)]">{proposal.status}</span></div><p className="mt-5 text-sm leading-6 text-zinc-700">{proposal.summary || proposal.description}</p>{proposal.openQuestions ? <div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><strong>Falta definir</strong><p className="mt-1">{proposal.openQuestions}</p><p className="mt-2">Respondelo en Senda AI y prepará nuevamente la propuesta.</p></div> : null}{canSubmit && proposal.status === "DRAFT" ? <button onClick={submit} disabled={sending} className="mt-6 rounded-xl bg-zinc-950 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{sending ? "Enviando…" : "Enviar al equipo"}</button> : null}{error ? <p className="mt-3 text-sm text-red-600">{error}</p> : null}</div></main>;
}
